project_id = "skrpxmkxehnuzmtkzuyo"

[functions.cleanup-old-orders]
verify_jwt = false

[functions.send-telegram-notification]
verify_jwt = false

[functions.send-whatsapp-notification]
verify_jwt = false

[functions.setup-admin]
verify_jwt = false

[functions.get-signed-payment-url]
verify_jwt = false